name: "Pull Request Validade Docs"

on: [pull_request]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: build docs
        run: yarn build