name: "Docs"

on:
  push:
    branches:
      - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: build docs
        run: yarn build
      
      - name: Branch protection OFF
        run: |
          curl --request PUT \
          --url 'https://api.github.com/repos/isjanebea/docsauro-hello-word/branches/gh-pages/protection' \
          --header 'Authorization: token ${{ secrets.PAT_CHANGE_BRANCH_PROTECTION_RULES_FROM_BEA }}' \
          --data '{"enforce_admins":false,"required_pull_request_reviews":null,"required_status_checks":null,"required_conversation_resolution":false,"restrictions":null,"required_linear_history":false}'
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: build

      - name: Branch protection ON
        run: |
          curl --request PUT \
          --url 'https://api.github.com/repos/isjanebea/docsauro-hello-word/branches/gh-pages/protection' \
          --header 'Authorization: token ${{ secrets.PAT_CHANGE_BRANCH_PROTECTION_RULES_FROM_BEA }}' \
          --header 'Accept: application/vnd.github.luke-cage-preview+json' \
          --data '{"enforce_admins":true,"required_pull_request_reviews":{"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2},"required_conversation_resolution":true,"required_status_checks":null,"restrictions":null,"required_linear_history":true}'